[GOOGLE_SERVICE_ACCOUNT_JSON]
type = "service_account"
project_id = "blog-auth-cms"
private_key_id = "5816a9037b1446dc0e976d0d88d3ac06cd729e10"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCjkD2S7bz46XMj
J37pSq75g6WNlUbFGsiU+psrd0jc5cnXOgG6TeHBzbKo5zstB9aM7xOEIE/kVOxy
DB5kyFIbxqCE/zZMHVb0CRPEVDM7J/vGuvLNZqHdYDBdZ/knhqt06XzXWaJEF6Rm
UCfGlVrelQygk7cvwNjNF9lOZd110SNuHFH2KQH7Bixbc4fZqQ1bH7dEfnbkCSLb
81KH4pYq/gYhCjMGNiT9pr06xfNMr4lo2BF+81jMZs7E4cSTkXJsNOjg20RcE9z7
tPqBT3VoiquNsUssj1+CNK4F93wTxHLof6umHRNZsGYw1KYJ4FCpiOs2cBBGHPv6
UCJId1XZAgMBAAECggEABS4Gj5F5IQSoAwm96bTvnoXzBC1HsOr7EnuIo1zmdF2c
yAGPN79xW6uzay832+JdT5hfP//gj9MgEf3v9RI1kxAcZsHVtIQSv1OadubEul+d
VPFely8kIQh216QFvnqNeC+DWg2KYQlcb509UtTJhfZNHVIepJCncDOyy81xim86
LVvQGwUNCvI6bD+oDqp88BdQTuWo0amFOnhZorDGk9bqT2owWlfuY/0c0bE2KSKE
XyL+guNLoz5j/cvAnK23kDmYB40Q1g6W7EbKgs/GIq3WNbpHLVLuLuBTH2BV4QcK
iy7xxzVFwAe8rEFmSS1Zjyw9OlqL4whq0nPTRYyZBQKBgQDU3tBqJL21+AXIwHh6
LX53lW5Wa5I0dwo1wyEK5UqY3t7cvQMK5TZNj9A23pLomZ0dtfrvj+/ATOEg64Jp
8aF/zDHLmJjf8pGzxOBXcPCtetJTdrcqIvYV5/zLWSVkf/nYZWxPOwgVF/DTTV8/
8qlNG1Tl+b1NMtRBuylYpUEXtQKBgQDEs/f9shtUZk/CpzA6OpCH2VXt2yQVj9ey
Z1DVOEee4sjU0gwVD8nOJqK8m4JtahJp6nXcWYw8bvcvQpA3hKH4DBAiEZlMOiov
t/9iYwIcZWUABLX94ihhlhwh8IMrA+FaLW/8oHwifVa3Ya7GTD/lgvdtIHR91+X2
krm1ipVUFQKBgFCuwz/3/Q/jmg2lJgTpCW457UBENX49QFlwRC3lCok2sDHqUiTn
C9YKFFk3s2cGEk8YkqwKWk0A1rOrkBqnwxa1RopspET9o8wHayC5Zf/a9a086d/G
sI9NBrvsZgfZmdEzYAIH1eBo2pa8VMXgK9tV6K/iIKYKBfmD/v/iYvGhAoGADcLt
gaE5SkFSKTMbK6e3PtnUqixfrOaAV6nkvNYQJKyHEmSTldGh87s+PWW/zTnTifdu
QXk+V2gIARVuE4RC9KCbbFbA29Vh6C6+PjrhBe2OEF9EADwXSSSAWVuDQbomxPFS
2WC87ojITVIXMSZafgsYlljj7X3yR7riJTJJ2jUCgYAZQOk4zXJbkQ1jnCtuDDnu
LeLGhMLNeDF5lD2o0Ncj3mXTMFMRYzyn8dZ1q+bSCsE3ESU6XmI8mrHsuqBmV8YD
M8lrpbxTJEzGVDXPertQsNhqgEqKoM46kYMCgXHrAA4j9s8neTSNl97dr2Q4VE18
xb68c+msrrP4W+9OTb3VbQ==
-----END PRIVATE KEY-----"""
client_email = "loss-time@blog-auth-cms.iam.gserviceaccount.com"
client_id = "108544579810610360801"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/loss-time%40blog-auth-cms.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
